### ISSUE TITLE
accept width parameter in bsModal?

### ISSUE THREAD

**Issue by happyshows** [ebailey78/shinyBS#27]
Hi,

It seems the default "large" size is not wide enough to host a datatable with a couple columns, it is possible to allow x-large or configurable width in this bsModal function?

**Comment by ebailey78** [comment]
I've been a little reluctant to do this because I don't want to deviate too far from standard bootstrap functionality but I've gotten this request several times so I've implemented a possible solution. Install the github version:

`devtools::install_github("ebailey78/shinyBS", ref = "shinyBS3")`

There is a width argument now. You have to provide units as part of the value so `width = "1000px"` or `width = "80%"` or any other acceptable css width unit.

Please let me know if you have any problems with this.

**Comment by happyshows** [comment]
thanks for the quick feedback.
